// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddConfiguredLibrary(arg1) {
  return window['go']['main']['App']['AddConfiguredLibrary'](arg1);
}

export function ApplyUpdate(arg1) {
  return window['go']['main']['App']['ApplyUpdate'](arg1);
}

export function CancelScan() {
  return window['go']['main']['App']['CancelScan']();
}

export function CheckCollisions(arg1, arg2) {
  return window['go']['main']['App']['CheckCollisions'](arg1, arg2);
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function ClearAppData() {
  return window['go']['main']['App']['ClearAppData']();
}

export function CopyFileToClipboard(arg1) {
  return window['go']['main']['App']['CopyFileToClipboard'](arg1);
}

export function CopyPackagesToLibrary(arg1, arg2, arg3) {
  return window['go']['main']['App']['CopyPackagesToLibrary'](arg1, arg2, arg3);
}

export function CutFileToClipboard(arg1) {
  return window['go']['main']['App']['CutFileToClipboard'](arg1);
}

export function DeleteFileToRecycleBin(arg1) {
  return window['go']['main']['App']['DeleteFileToRecycleBin'](arg1);
}

export function DisableOldVersions(arg1, arg2, arg3) {
  return window['go']['main']['App']['DisableOldVersions'](arg1, arg2, arg3);
}

export function DownloadPackage(arg1, arg2) {
  return window['go']['main']['App']['DownloadPackage'](arg1, arg2);
}

export function FinishSetup() {
  return window['go']['main']['App']['FinishSetup']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConfiguredLibraries() {
  return window['go']['main']['App']['GetConfiguredLibraries']();
}

export function GetDiskSpace(arg1) {
  return window['go']['main']['App']['GetDiskSpace'](arg1);
}

export function GetFilters(arg1) {
  return window['go']['main']['App']['GetFilters'](arg1);
}

export function GetLibraryCounts(arg1) {
  return window['go']['main']['App']['GetLibraryCounts'](arg1);
}

export function GetLocalIP() {
  return window['go']['main']['App']['GetLocalIP']();
}

export function GetPackageContents(arg1) {
  return window['go']['main']['App']['GetPackageContents'](arg1);
}

export function GetPackageThumbnail(arg1) {
  return window['go']['main']['App']['GetPackageThumbnail'](arg1);
}

export function GetUserDownloadsDir() {
  return window['go']['main']['App']['GetUserDownloadsDir']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InstallFiles(arg1, arg2) {
  return window['go']['main']['App']['InstallFiles'](arg1, arg2);
}

export function IsConfigured() {
  return window['go']['main']['App']['IsConfigured']();
}

export function IsServerRunning() {
  return window['go']['main']['App']['IsServerRunning']();
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function OpenAppDataFolder() {
  return window['go']['main']['App']['OpenAppDataFolder']();
}

export function OpenFolderInExplorer(arg1) {
  return window['go']['main']['App']['OpenFolderInExplorer'](arg1);
}

export function RemoveConfiguredLibrary(arg1) {
  return window['go']['main']['App']['RemoveConfiguredLibrary'](arg1);
}

export function ReorderConfiguredLibraries(arg1) {
  return window['go']['main']['App']['ReorderConfiguredLibraries'](arg1);
}

export function ResolveConflicts(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResolveConflicts'](arg1, arg2, arg3);
}

export function RestartApp() {
  return window['go']['main']['App']['RestartApp']();
}

export function RevokeSession(arg1) {
  return window['go']['main']['App']['RevokeSession'](arg1);
}

export function ScanPackages(arg1) {
  return window['go']['main']['App']['ScanPackages'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SetAlwaysOnTop(arg1) {
  return window['go']['main']['App']['SetAlwaysOnTop'](arg1);
}

export function SetAuthPollInterval(arg1) {
  return window['go']['main']['App']['SetAuthPollInterval'](arg1);
}

export function SetMinimizeOnClose(arg1) {
  return window['go']['main']['App']['SetMinimizeOnClose'](arg1);
}

export function SetPassword(arg1) {
  return window['go']['main']['App']['SetPassword'](arg1);
}

export function SetPublicAccess(arg1) {
  return window['go']['main']['App']['SetPublicAccess'](arg1);
}

export function SetServerEnabled(arg1) {
  return window['go']['main']['App']['SetServerEnabled'](arg1);
}

export function SetServerPort(arg1) {
  return window['go']['main']['App']['SetServerPort'](arg1);
}

export function StartServer() {
  return window['go']['main']['App']['StartServer']();
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}

export function TogglePackage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['TogglePackage'](arg1, arg2, arg3, arg4);
}

export function UpdatePassword(arg1) {
  return window['go']['main']['App']['UpdatePassword'](arg1);
}

export function UpdateServerLibraries(arg1) {
  return window['go']['main']['App']['UpdateServerLibraries'](arg1);
}
