// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CopyFileToClipboard(arg1:string):Promise<void>;

export function CutFileToClipboard(arg1:string):Promise<void>;

export function DeleteFileToRecycleBin(arg1:string):Promise<void>;

export function DisableOldVersions(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DownloadPackage(arg1:string,arg2:string):Promise<void>;

export function GetFilters(arg1:string):Promise<Array<string>>;

export function GetLocalIP():Promise<string>;

export function GetPackageContents(arg1:string):Promise<Array<models.PackageContent>>;

export function GetUserDownloadsDir():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function InstallFiles(arg1:Array<string>,arg2:string):Promise<Array<string>>;

export function OpenFolderInExplorer(arg1:string):Promise<void>;

export function ScanPackages(arg1:string):Promise<models.ScanResult>;

export function SelectDirectory():Promise<string>;

export function SetAlwaysOnTop(arg1:boolean):Promise<void>;

export function SetMinimizeOnClose(arg1:boolean):Promise<void>;

export function StartServer(arg1:string,arg2:string):Promise<void>;

export function StopServer():Promise<void>;

export function TogglePackage(arg1:string,arg2:boolean,arg3:string,arg4:boolean):Promise<string>;
