// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {updater} from '../models';
import {manager} from '../models';
import {models} from '../models';

export function AddConfiguredLibrary(arg1:string):Promise<void>;

export function ApplyUpdate(arg1:string):Promise<void>;

export function CancelScan():Promise<void>;

export function CheckForUpdates():Promise<updater.UpdateInfo>;

export function ClearAppData():Promise<void>;

export function CopyFileToClipboard(arg1:string):Promise<void>;

export function CopyPackagesToLibrary(arg1:Array<string>,arg2:string,arg3:boolean):Promise<Array<string>>;

export function CutFileToClipboard(arg1:string):Promise<void>;

export function DeleteFileToRecycleBin(arg1:string):Promise<void>;

export function DisableOldVersions(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DownloadPackage(arg1:string,arg2:string):Promise<void>;

export function FinishSetup():Promise<void>;

export function GetAppVersion():Promise<string>;

export function GetConfiguredLibraries():Promise<Array<string>>;

export function GetDiskSpace(arg1:string):Promise<manager.DiskSpaceInfo>;

export function GetFilters(arg1:string):Promise<Array<string>>;

export function GetLibraryCounts(arg1:Array<string>):Promise<Record<string, number>>;

export function GetLocalIP():Promise<string>;

export function GetPackageContents(arg1:string):Promise<Array<models.PackageContent>>;

export function GetPackageThumbnail(arg1:string):Promise<string>;

export function GetUserDownloadsDir():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function InstallFiles(arg1:Array<string>,arg2:string):Promise<Array<string>>;

export function IsConfigured():Promise<boolean>;

export function OpenAppDataFolder():Promise<void>;

export function OpenFolderInExplorer(arg1:string):Promise<void>;

export function RemoveConfiguredLibrary(arg1:string):Promise<void>;

export function ReorderConfiguredLibraries(arg1:Array<string>):Promise<void>;

export function ResolveConflicts(arg1:string,arg2:Array<string>,arg3:string):Promise<manager.ResolveConflictResult>;

export function RestartApp():Promise<void>;

export function ScanPackages(arg1:string):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SetAlwaysOnTop(arg1:boolean):Promise<void>;

export function SetMinimizeOnClose(arg1:boolean):Promise<void>;

export function StartServer(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function StopServer():Promise<void>;

export function TogglePackage(arg1:string,arg2:boolean,arg3:string,arg4:boolean):Promise<string>;

export function UpdateServerLibraries(arg1:Array<string>):Promise<void>;
