// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyFileToClipboard(arg1) {
  return window['go']['main']['App']['CopyFileToClipboard'](arg1);
}

export function CopyPackagesToLibrary(arg1, arg2, arg3) {
  return window['go']['main']['App']['CopyPackagesToLibrary'](arg1, arg2, arg3);
}

export function CutFileToClipboard(arg1) {
  return window['go']['main']['App']['CutFileToClipboard'](arg1);
}

export function DeleteFileToRecycleBin(arg1) {
  return window['go']['main']['App']['DeleteFileToRecycleBin'](arg1);
}

export function DisableOldVersions(arg1, arg2, arg3) {
  return window['go']['main']['App']['DisableOldVersions'](arg1, arg2, arg3);
}

export function DownloadPackage(arg1, arg2) {
  return window['go']['main']['App']['DownloadPackage'](arg1, arg2);
}

export function GetFilters(arg1) {
  return window['go']['main']['App']['GetFilters'](arg1);
}

export function GetLocalIP() {
  return window['go']['main']['App']['GetLocalIP']();
}

export function GetPackageContents(arg1) {
  return window['go']['main']['App']['GetPackageContents'](arg1);
}

export function GetUserDownloadsDir() {
  return window['go']['main']['App']['GetUserDownloadsDir']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InstallFiles(arg1, arg2) {
  return window['go']['main']['App']['InstallFiles'](arg1, arg2);
}

export function OpenFolderInExplorer(arg1) {
  return window['go']['main']['App']['OpenFolderInExplorer'](arg1);
}

export function ScanPackages(arg1) {
  return window['go']['main']['App']['ScanPackages'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SetAlwaysOnTop(arg1) {
  return window['go']['main']['App']['SetAlwaysOnTop'](arg1);
}

export function SetMinimizeOnClose(arg1) {
  return window['go']['main']['App']['SetMinimizeOnClose'](arg1);
}

export function StartServer(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartServer'](arg1, arg2, arg3);
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}

export function TogglePackage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['TogglePackage'](arg1, arg2, arg3, arg4);
}

export function UpdateServerLibraries(arg1) {
  return window['go']['main']['App']['UpdateServerLibraries'](arg1);
}
