// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function DisableOldVersions(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetFilters(arg1:string):Promise<Array<string>>;

export function Greet(arg1:string):Promise<string>;

export function InstallFiles(arg1:Array<string>,arg2:string):Promise<Array<string>>;

export function ScanPackages(arg1:string):Promise<Array<models.VarPackage>>;

export function SelectDirectory():Promise<string>;

export function ToggleFavorite(arg1:string):Promise<void>;

export function ToggleHidden(arg1:string):Promise<void>;

export function TogglePackage(arg1:string,arg2:boolean,arg3:string):Promise<string>;
