package updater

import (
	"crypto/ed25519"
	"crypto/sha256"
	"encoding/base64"
	"fmt"
)

// PublicKey is the Ed25519 public key corresponding to the private key used by the releaser.
// Generated by cmd/genkeys/main.go
var PublicKey = "9qhjmSs/QEYhxEEN/6blfST64pNSum6yyhzRh86d2cA="

// VerifySignature checks if the provided data matches the base64-encoded signature
func VerifySignature(data []byte, signatureBase64 string) error {
	// 1. Decode Public Key
	pubParams, err := base64.StdEncoding.DecodeString(PublicKey)
	if err != nil {
		return fmt.Errorf("invalid embedded public key: %v", err)
	}
	if len(pubParams) != ed25519.PublicKeySize {
		return fmt.Errorf("invalid public key size: %d", len(pubParams))
	}

	// 2. Decode Signature
	sig, err := base64.StdEncoding.DecodeString(signatureBase64)
	if err != nil {
		return fmt.Errorf("invalid signature encoding: %v", err)
	}
	if len(sig) != ed25519.SignatureSize {
		return fmt.Errorf("invalid signature size: %d", len(sig))
	}

	// 3. Verify
	hash := sha256.Sum256(data)
	valid := ed25519.Verify(ed25519.PublicKey(pubParams), hash[:], sig)
	if !valid {
		return fmt.Errorf("signature verification failed")
	}

	return nil
}
